apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  labels:
    app: testpod1
spec:
  nodeName: k8s-w1
  containers:
  - name: netshoot-pod
    image: nicolaka/netshoot
    command: ["tail"]
    args: ["-f", "/dev/null"]
  terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod2
  labels:
    app: testpod2
spec:
  nodeName: k8s-w2
  containers:
  - name: netshoot-pod
    image: nicolaka/netshoot
    command: ["tail"]
    args: ["-f", "/dev/null"]
  terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod3
  labels:
    app: testpod3
spec:
  nodeName: k8s-w2
  containers:
  - name: netshoot-pod
    image: nicolaka/netshoot
    command: ["tail"]
    args: ["-f", "/dev/null"]
  terminationGracePeriodSeconds: 0