# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mycluster
spec:
  instances: 3
  storage:
    size: 3Gi
  postgresql:
    pg_hba:
      - host all postgres all trust
  minSyncReplicas: 1
  maxSyncReplicas: 2s